- name: Install & Configure Nginx Proxy
  hosts: "{{node_group}}"
  remote_user: "{{APACHE_USER}}"
  become: yes
  vars_files:
    - role-management/apache/vars/apache-vars.yml
    - role-management/ipaddress/vars/ipaddress-vars.yml
    - role-management/test/vars/test-vars.yml
    - sudoer_file
  roles:
    - role-management/apache