- name: Target Machine (Ubunt 20.04) Update [ apt update]
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install OpenSSL  ( apt install openssl )
  apt:
    name: openssl
    update_cache: yes
    state: latest

- name: Copy SSLCertificate.sh to {{ CERTIFICATE_ROOT }}
  template:
    src: SSLCertificate.sh.j2
    dest: "{{COMMON_DIR}}/SSLCertificate.sh"
    owner: "{{ REMOTE_USER }}"
    group: "{{ REMOTE_USER }}"
    mode: '0775'

- name: Executing the permission change script
  shell: sh SSLCertificate.sh > {{COMMON_DIR}}/SSLCertificate.log 2>&1
  args:
    chdir: "{{COMMON_DIR}}"

