- name: "Allow everything and enable UFW"
  ufw:
    state: enabled
    policy: allow

- name: Set logging
  ufw:
    logging: on

- name: "UFW - Allow HTTP on port {{ HTTP_PORT }}"
  ufw:
    rule: allow
    port: "{{ HTTP_PORT }}"
    proto: tcp

- name: "UFW - Allow HTTPS on port {{ HTTP_PORT }}"
  ufw:
    rule: allow
    port: "{{ HTTPS_PORT }}"
    proto: tcp



