- name: Install net-tools
  apt:
    name: net-tools
    update_cache: yes
    state: latest

- name: Copy Find IP Address Script
  template:
    src: find_ipaddress.sh.j2
    dest: "{{COMMON_DIR}}/find_ipaddress.sh"
    mode: '0755'

- name: Executing the Find IPAddess  script
  shell: sh find_ipaddress.sh > {{COMMON_DIR}}/find_ipaddress.log 2>&1
  args:
    chdir: "{{COMMON_DIR}}"

- include: hostconfig.yml