- name: Install net-tools
  apt:
    name: net-tools
    update_cache: yes
    state: latest

- name: Copy Find IP Address Script
  template:
    src: find_ipaddress.sh.j2
    dest: "/tmp/find_ipaddress.sh"
    mode: '0755'
- name: Run Find IP Address Script
  template:
    shell: /usr/bin/bash find_ipaddress.sh

- include: hostconfig.yml